### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by OmarCaf** [fs/harvest-notifier#27]
Hi,

great work about this application, I want to enable also "Refresh" button that needs
<img width="734" alt="Schermata 2020-12-03 alle 17 26 16" src="https://user-images.githubusercontent.com/56885/101057834-c616ab00-358c-11eb-9098-653a2f4e7e7b.png">
 interaction enabled on the slack App site but I'm sure about what URL I need to add in the field (see screenshot)

**Comment by Vadim-Kurnatovskiy** [comment]
Hi, @OmarCaf! I am glad to hear that our application can help you! You need to use a heroku application link as Request URL(like on the screenshot below). If you need help with creating or configuring heroku application, I am ready to help you.
Also I can update README and add this info for clarification. Thank you!
![image](https://user-images.githubusercontent.com/49876756/102022546-9c356380-3d98-11eb-9035-5dc173dd629a.png)
